#!/usr/bin/env python3
"""
Trajectory-based PPO training script for multi-turn conversation models (Modular Version).
Implements true on-policy PPO where entire conversations are treated as trajectories,
with rewards computed at each turn: ([U1], [A1]), ([U1,A1,U2], [A2]), etc.

This version uses modular reward calculators for better maintainability and extensibility.
Includes improved model loading with vLLM support for faster inference.

Architecture:
- Assistant responses: Generated by PPO model being trained (optionally accelerated with vLLM)
- User responses: Generated by UserSimulator via Bedrock (runs in parallel)
- Trajectory generation: Multiple conversations processed simultaneously

Example usage:
CUDA_VISIBLE_DEVICES=4,5,6,7 torchrun --master_port=56600 --nnodes=1 --nproc_per_node=4 -m scripts.train.trajectory_ppo_modular \
    --dataset_repo path/to/initial_prompts.csv \
    --model_name outputs/sft/my_model \
    --base_model_name meta-llama/Llama-3.1-8B-Instruct \
    --output_dir outputs/trajectory_ppo/my_model \
    --reward_type entropy \
    --max_turns 5 \
    --batch_size 4 \
    --mini_batch_size 2 \
    --learning_rate 1e-6 \
    --use_vllm \
    --user_meta_prompt prompts/user_prompt.txt
"""

from __future__ import annotations

import sys
import os

# Automatically add the root project directory to sys.path
project_root = os.path.abspath(os.path.join(os.path.dirname(__file__), '..'))
if project_root not in sys.path:
    sys.path.append(project_root)

import argparse, json
import torch.distributed as dist
import wandb
import hashlib
from typing import Tuple, Optional, List, Dict, Any
from dotenv import load_dotenv
import numpy as np
import copy
from tqdm import tqdm
from packaging import version
import asyncio
import math
import tiktoken
from concurrent.futures import ThreadPoolExecutor, as_completed

import trl
from trl import AutoModelForCausalLMWithValueHead, PPOConfig, PPOTrainer
# if version.parse(trl.__version__) > version.parse("0.10.1"):
#     raise RuntimeError(f"For this script, `trl` version {trl.__version__} is incompatible. Please install trl<-0.10.1 to run this script.")

from peft import PeftConfig, PeftModel, LoraConfig, get_peft_model

import torch
from transformers import (
    AutoModelForCausalLM,
    AutoTokenizer,
    BitsAndBytesConfig,
)
from datasets import Dataset, DatasetDict, load_dataset, load_from_disk, Features, Value, Sequence
import ast
import random
from utils.fixseed import fix_all_seeds

# Import simulators
from simulators.user_simulator import UserSimulator

from evaluation.rewards import (
    RewardCalculatorFactory,
    create_reward_calculator,
    print_dependency_status
)

def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser("Trajectory-based multiturn PPO trainer (Modular)")

    # Data / paths
    p.add_argument("--dataset_repo", type=str, required=True)
    p.add_argument("--dataset_name", type=str, default="movie_rec")
    p.add_argument("--metric_names", nargs="+", default=["accuracy", "token_amount"])
    p.add_argument("--user_generation_kwargs", type=json.loads, default="{}")
    p.add_argument("--assistant_generation_kwargs", type=json.loads, default="{}")
    p.add_argument("--reward_generation_kwargs", type=json.loads, default="{}")
    p.add_argument("--metric_weights", type=float, nargs="+", default=[1.0, 1.0, -0.1],
                   help="Weights for metrics: [hit_rate, interactivity, token_efficiency] for collabllm")
    p.add_argument("--max_new_turns", type=int, default=4)
    p.add_argument("--num_samples", type=int, default=3)
    p.add_argument("--user_meta_prompt", type=str, default=None, help="Path to user meta prompt file")

    p.add_argument("--output_dir", type=str, required=True)
    p.add_argument("--resume_ckpt_dir", type=str, default=None)

    p.add_argument('--user_temperature', type=float, default=0.7,
                        help='Temperature for user simulation')
    p.add_argument('--user_max_tokens', type=int, default=150,
                        help='Maximum tokens for user simulation')
    

    # Base / adapter models
    p.add_argument("--model_name", type=str, required=True)
    p.add_argument("--base_model_name", type=str, required=True)
    p.add_argument("--ref_model_name", type=str, default=None)

    # LoRA configuration for fresh training
    p.add_argument("--lora_r", type=int, default=32, help="LoRA rank")
    p.add_argument("--lora_alpha", type=int, default=16, help="LoRA alpha")
    p.add_argument("--lora_dropout", type=float, default=0.1, help="LoRA dropout")
    p.add_argument("--lora_target_modules", nargs="+", default=["q_proj", "v_proj"], help="LoRA target modules")

    # vLLM configuration
    p.add_argument("--use_vllm", action="store_true", default=False, help="Use vLLM for faster inference")
    p.add_argument("--gpu_memory_utilization", type=float, default=0.2, help="GPU memory utilization for vLLM")
    p.add_argument("--max_model_len", type=int, default=4096, help="Maximum model length for vLLM")
    
    # Trajectory PPO specific
    p.add_argument("--reward_type", type=str, choices=["collabllm", "entropy", "simple"], default="entropy",
                   help="Type of reward to use: collabllm (hit_rate + interactivity + token_efficiency), entropy (turn-level), or simple (length-based)")
    p.add_argument("--max_turns", type=int, default=5,
                   help="Maximum number of turns in generated conversations")
    
    # Entropy reward specific parameters
    p.add_argument("--entropy_model", type=str, default="us.meta.llama3-1-8b-instruct-v1:0")
    p.add_argument("--entropy_samples", type=int, default=5)
    p.add_argument("--entropy_items", type=int, default=5)
    
    # CollabLLM reward specific parameters  
    p.add_argument("--interactivity_model", type=str, default="us.anthropic.claude-3-7-sonnet-20250219-v1:0")
    p.add_argument("--max_eval_turns", type=int, default=11)
    p.add_argument("--encoding_name", type=str, default="cl100k_base")

    # PPO specific  
    p.add_argument("--num_ppo_epochs", type=int, default=4)
    p.add_argument("--batch_size", type=int, default=8)
    p.add_argument("--mini_batch_size", type=int, default=2)   
    p.add_argument("--use_score_scaling", action="store_true", default=False)
    p.add_argument("--use_score_norm", action="store_true", default=False)

    # Optim & schedule
    p.add_argument("--seed", type=int, default=42)
    p.add_argument("--learning_rate", type=float, default=1e-6)
    p.add_argument("--num_train_epochs", type=int, default=3)
    p.add_argument("--gradient_accumulation_steps", type=int, default=8)
    p.add_argument("--save_steps", type=int, default=50)
    p.add_argument("--save_total_limit", type=int, default=3)
    p.add_argument("--logging_steps", type=int, default=1)
    p.add_argument("--max_metric_workers", type=int, default=4)
    
    # Generation parameters
    p.add_argument("--top_p", type=float, default=0.9)
    p.add_argument("--temperature", type=float, default=0.8)
    p.add_argument("--max_new_tokens", type=int, default=256)
    
    # Precision / hardware
    p.add_argument("--device", type=str, default="cuda")
    p.add_argument("--use_4bit", action="store_true", default=False)

    # Tracking
    p.add_argument("--wandb_project", type=str)
    p.add_argument("--wandb_entity", type=str)
    p.add_argument("--push_to_hub", action="store_true")
    p.add_argument("--hf_org", type=str)
    p.add_argument("--debug", action="store_true")

    # Optional JSON/YAML override
    p.add_argument("--config_file", type=str)

    args = p.parse_args()
    if args.config_file:
        with open(args.config_file) as f:
            override = json.load(f) if args.config_file.endswith(".json") else \
                       __import__("yaml").safe_load(f)
        for k, v in override.items():
            setattr(args, k, v)
    return args

def _uniform_split(full_ds: Dataset, *, eval_ratio: float, n_eval: Optional[int], seed: int) -> DatasetDict:
    k = n_eval if n_eval is not None else int(eval_ratio * len(full_ds))
    k = min(k, len(full_ds))
    eval_idx = set(random.sample(range(len(full_ds)), k=k))
    train_idx = [i for i in range(len(full_ds)) if i not in eval_idx]

    return DatasetDict({
        "train": full_ds.select(train_idx),
        "eval": full_ds.select(sorted(eval_idx)),
    })

# --------------------------------------------------------------------------- #
# Utilities
# --------------------------------------------------------------------------- #
def load_model_and_tokenizer(
    model_name: str,
    base_model_name: str,
    bnb_cfg: Optional[BitsAndBytesConfig],
    lora_cfg: Optional[LoraConfig] = None,
    device: str = "cuda",
    is_eval: bool = False,
    gpu_memory_utilization: float = 0.6,
    max_model_len: int = 4096,
    use_vllm: bool = False,
) -> Tuple[torch.nn.Module, AutoTokenizer, Optional[Any]]:
    """
    Load model and tokenizer with support for both PEFT checkpoints and fresh LoRA training.
    
    Args:
        model_name: Path to model (can be PEFT checkpoint or base model)
        base_model_name: Base model for tokenizer and fallback
        bnb_cfg: Quantization config
        lora_cfg: LoRA config for new training (if not loading existing PEFT)
        device: Device to load on
        is_eval: Whether this is for evaluation
        gpu_memory_utilization: GPU memory for vLLM
        max_model_len: Max sequence length
        use_vllm: Whether to initialize vLLM engine
    
    Returns:
        (model, tokenizer, vllm_engine)
    """
    
    # Strategy 1: Try to load as existing PEFT checkpoint
    if os.path.exists(model_name):
        try:
            # Check if it's a PEFT checkpoint
            peft_config_path = os.path.join(model_name, "adapter_config.json")
            if os.path.exists(peft_config_path):
                print(f"Loading PEFT checkpoint from: {model_name}")
                pc = PeftConfig.from_pretrained(model_name)
                print(f"  Base model: {pc.base_model_name_or_path}")
                print(f"  PEFT type: {pc.peft_type}")
                
                model = AutoModelForCausalLMWithValueHead.from_pretrained(
                    model_name,
                    device_map={"": device},
                    quantization_config=bnb_cfg,
                    is_trainable=not is_eval,
                    trust_remote_code=True,
                )
                tokenizer_base = pc.base_model_name_or_path
            else:
                # It's a regular saved model
                print(f"Loading saved model from: {model_name}")
                model = AutoModelForCausalLMWithValueHead.from_pretrained(
                    model_name,
                    device_map={"": device},
                    quantization_config=bnb_cfg,
                    is_trainable=not is_eval,
                    trust_remote_code=True,
                )
                tokenizer_base = base_model_name
                
        except Exception as e:
            print(f"Failed to load from {model_name}: {e}")
            print(f"Falling back to base model: {base_model_name}")
            model = None
    else:
        print(f"Model path {model_name} does not exist")
        model = None
    
    # Strategy 2: Load base model + apply LoRA config
    if model is None:
        print(f"Loading base model: {base_model_name}")
        if lora_cfg:
            print(f"  Applying LoRA config: r={lora_cfg.r}, alpha={lora_cfg.lora_alpha}")
        
        model = AutoModelForCausalLMWithValueHead.from_pretrained(
            base_model_name,
            trust_remote_code=True,
            device_map={"": device},
            peft_config=lora_cfg,
            quantization_config=bnb_cfg,
            is_trainable=not is_eval,
        )
        tokenizer_base = base_model_name
    
    # Load tokenizer
    tok = AutoTokenizer.from_pretrained(tokenizer_base, trust_remote_code=True)
    tok.padding_side, tok.pad_token = ("left" if is_eval else "right"), tok.eos_token
    
    # Print parameter info
    trainable = sum(p.numel() for p in model.parameters() if p.requires_grad)
    total = sum(p.numel() for p in model.parameters())
    print(f"Trainable params: {trainable:,}/{total:,} ({trainable/total:.2%})")
    
    # Optional vLLM initialization
    vllm_engine = None
    if use_vllm:
        try:
            from vllm import LLM
            vllm_args = {
                "model": tokenizer_base,
                "dtype": "bfloat16" if torch.cuda.is_bf16_supported() else "float16",
                "distributed_executor_backend": "external_launcher",
                "gpu_memory_utilization": gpu_memory_utilization,
                "max_model_len": max_model_len,
            }
            
            # Only add quantization args if actually using quantization
            if bnb_cfg:
                vllm_args["quantization"] = "bitsandbytes"
                vllm_args["load_format"] = "bitsandbytes"
            
            # Only add LoRA args if using LoRA
            if lora_cfg or hasattr(model.pretrained_model, 'peft_config'):
                vllm_args["enable_lora"] = True
                vllm_args["max_lora_rank"] = lora_cfg.r if lora_cfg else 32
            
            vllm_engine = LLM(**vllm_args)
            print("✓ vLLM engine initialized")
        except Exception as e:
            print(f"⚠️ Failed to initialize vLLM: {e}")
            vllm_engine = None

    return model, tok, vllm_engine

def load_csv_dataset(dataset_repo: str, eval_ratio: float = 0.0, seed: int = 42):
    """Load initial prompts from CSV"""
    ds = load_dataset("csv", data_files=dataset_repo, encoding="utf-8", encoding_errors="ignore")

    return _uniform_split(ds['train'], eval_ratio=eval_ratio, seed=seed, n_eval=None)

def collator(data):
    return {key: [d[key] for d in data] for key in data[0]}

def generate_vllm_parallel(model, tokenizer, vllm_engine, prompts, generation_kwargs):
    """
    Generate completions using vLLM for parallel processing.
    Adapted from the CollabLLM ChatSessionSimulator._batch_generate_with_vllm method.
    """
    try:
        from vllm import SamplingParams
        
        # Format prompts for model input
        formatted_prompts = []
        for prompt in prompts:
            if isinstance(prompt, list):
                # Chat format
                prompt_text = tokenizer.apply_chat_template(
                    prompt, 
                    tokenize=False, 
                    add_generation_prompt=True
                )
            else:
                # String format
                prompt_text = prompt
            formatted_prompts.append(prompt_text)
        
        # Set up sampling parameters
        sampling_params = SamplingParams(
            temperature=generation_kwargs.get("temperature", 0.8),
            top_p=generation_kwargs.get("top_p", 0.9),
            max_tokens=generation_kwargs.get("max_tokens", generation_kwargs.get("max_new_tokens", 256)),
            n=generation_kwargs.get("n", 1),
            top_k=generation_kwargs.get("top_k", 50),
            # Add these for stability:
            repetition_penalty=1.0,
            frequency_penalty=0.0,
            presence_penalty=0.0,
        )
        
        # Generate with vLLM
        outputs = vllm_engine.generate(formatted_prompts, sampling_params)
        
        # Extract completion token IDs and prompt token IDs
        completion_ids = []
        prompt_ids = []
        
        for output in outputs:
            prompt_token_ids = torch.LongTensor(output.prompt_token_ids)
            completion_token_ids = torch.LongTensor(output.outputs[0].token_ids)
            
            prompt_ids.append(prompt_token_ids)
            completion_ids.append(completion_token_ids)
        
        return prompt_ids, completion_ids
    
    except Exception as e:
        print(f"vLLM generation failed: {e}")
        # Fallback to standard generation
        return generate_transformers_fallback(model, tokenizer, prompts, generation_kwargs)
    
def generate_transformers_fallback(model, tokenizer, prompts, generation_kwargs):
    """
    Fallback generation using standard transformers when vLLM fails.
    """
    prompt_ids = []
    completion_ids = []
    
    for prompt in prompts:
        if isinstance(prompt, list):
            # Chat format
            prompt_text = tokenizer.apply_chat_template(
                prompt, 
                tokenize=False, 
                add_generation_prompt=True
            )
        else:
            # String format
            prompt_text = prompt
        
        # Tokenize
        inputs = tokenizer(prompt_text, return_tensors="pt", padding=True, truncation=True)
        inputs = {k: v.to(model.device) for k, v in inputs.items()}
        
        # Generate response
        with torch.no_grad():
            outputs = model.generate(
                inputs["input_ids"],
                max_new_tokens=generation_kwargs.get("max_new_tokens", 256),
                temperature=generation_kwargs.get("temperature", 0.8),
                top_p=generation_kwargs.get("top_p", 0.9),
                do_sample=True,
                pad_token_id=tokenizer.pad_token_id,
                eos_token_id=tokenizer.eos_token_id,
            )
        
        # Extract only the new tokens
        prompt_token_ids = inputs["input_ids"][0]
        completion_token_ids = outputs[0][len(prompt_token_ids):]
        
        prompt_ids.append(prompt_token_ids)
        completion_ids.append(completion_token_ids)
    
    return prompt_ids, completion_ids

def _messages_to_prompt(messages: List[Dict[str, str]]) -> str:
    """Convert messages to simple prompt format"""
    prompt_parts = []

    prompt_parts.append(f"System: You are a helpful movie recommendation assistant. Provide personalized movie suggestions based on user preferences and engage in natural conversation about movies.\n")
    
    if not isinstance(messages, list):
        messages = json.loads(messages)
    for msg in messages:
        role = msg["role"]
        content = msg["content"]
    
        if role == "user":
            prompt_parts.append(f"User: {content}\n")
        elif role == "assistant":
            prompt_parts.append(f"Assistant: {content}\n")
    
    prompt_parts.append("Assistant: ")  # Prompt for assistant response
    return "".join(prompt_parts)

def main() -> None:
    args = parse_args()
    os.makedirs(args.output_dir, exist_ok=True)
    fix_all_seeds(args.seed)

    local_rank = int(os.environ.get('LOCAL_RANK', '0'))
    dist.init_process_group(backend='nccl', init_method=None)
    torch.cuda.set_device(local_rank)
    dist.barrier()

    # Dataset loading
    ds = load_csv_dataset(args.dataset_repo, eval_ratio=0., seed=args.seed)

    # Bits-and-bytes
    bnb_cfg = BitsAndBytesConfig(
        load_in_4bit=True,
        bnb_4bit_quant_type="nf4",
        bnb_4bit_use_double_quant=False,
        bnb_4bit_compute_dtype=torch.bfloat16,
    ) if args.use_4bit else None

    # Create LoRA config if we're doing fresh training
    lora_cfg = None
    if not os.path.exists(args.model_name) or not os.path.exists(os.path.join(args.model_name, "adapter_config.json")):
        lora_cfg = LoraConfig(
            r=args.lora_r,
            lora_alpha=args.lora_alpha,
            lora_dropout=args.lora_dropout,
            target_modules=args.lora_target_modules,
            bias="none",
            task_type="CAUSAL_LM",
        )
        print(f"Created LoRA config: r={lora_cfg.r}, alpha={lora_cfg.lora_alpha}, dropout={lora_cfg.lora_dropout}")

    # Load PPO model (the one being trained)
    model, tok, vllm_engine = load_model_and_tokenizer(
        args.model_name,
        args.base_model_name,
        bnb_cfg=bnb_cfg,
        lora_cfg=lora_cfg,
        device=args.device,
        is_eval=False,
        gpu_memory_utilization=args.gpu_memory_utilization,
        max_model_len=args.max_model_len,
        use_vllm=args.use_vllm,
    )

    # Load reference model if specified
    ref_model = None
    ref_vllm_engine = None
    if args.ref_model_name:
        ref_model, _, ref_vllm_engine = load_model_and_tokenizer(
            args.ref_model_name,
            args.base_model_name,
            bnb_cfg=bnb_cfg,
            lora_cfg=None,  # Reference model typically doesn't need LoRA
            device=args.device,
            is_eval=True,
            gpu_memory_utilization=args.gpu_memory_utilization,
            max_model_len=args.max_model_len,
            use_vllm=False,  # Reference model doesn't need vLLM
        )

    # W&B
    if args.wandb_project and os.environ.get("LOCAL_RANK", "0") == "0":
        wandb.init(
            project=args.wandb_project,
            entity=args.wandb_entity,
            name=args.output_dir.replace("/", "_"),
            config=vars(args),
            save_code=True,
            job_type="train",
        )

    # PPO Config
    ppo_config = PPOConfig(
        batch_size=args.batch_size,
        mini_batch_size=args.mini_batch_size,
        gradient_accumulation_steps=args.gradient_accumulation_steps,
        learning_rate=args.learning_rate,
        ppo_epochs=args.num_ppo_epochs,
        exp_name=args.output_dir.replace("/", "_"),
        remove_unused_columns=False,
        is_peft_model=True,
        use_score_scaling=args.use_score_scaling, 
        use_score_norm=args.use_score_norm,
        kl_penalty = "full"
    )

    # PPO Trainer
    trainer = PPOTrainer(
        model=model,
        ref_model=ref_model,
        config=ppo_config,
        dataset=ds["train"],
        tokenizer=tok,
        data_collator=collator
    )

    # Initialize trajectory components using modular reward system
    reward_calculator = RewardCalculatorFactory.create_from_args(args)
    print(f"Initialized {args.reward_type} reward calculator")

    ######################## TRAINING LOOP ########################
    def dataloader():
        epoch = 0
        dataloader_iter = iter(trainer.dataloader)
        while True:
            try:
                yield next(dataloader_iter)
            except StopIteration:
                epoch += 1
                if epoch >= args.num_train_epochs:
                    break
                dataloader_iter = iter(trainer.dataloader)
                yield next(dataloader_iter)

    total_steps = sum(1 for _ in tqdm(dataloader()))
    print(f'************** total steps = {total_steps} **************')

    step = 0
    ppo_steps = 0
    for batch in tqdm(dataloader(), total=total_steps):
        step += 1
        
        # Extract prompts from batch
        prompts = batch["prompt"]

        if local_rank == 0:  # Only print from main process
            print(f"\n{'='*50} Step {step} {'='*50}")
            print(f"Generating {len(prompts)} completions in parallel using {'vLLM' if vllm_engine else 'transformers'}...")

        # Generate responses using vLLM (parallel) or transformers (fallback)
        model.train()
            
        generation_kwargs = copy.deepcopy(args.assistant_generation_kwargs)
        generation_kwargs.update({
            "temperature": args.temperature,
            "top_p": args.top_p,
            "max_new_tokens": args.max_new_tokens,
        })
        
        
        prompts = [_messages_to_prompt(prompt) for prompt in prompts]

        if vllm_engine:
            prompt_ids, completion_ids = generate_vllm_parallel(
                model.pretrained_model, tok, vllm_engine, prompts, generation_kwargs
            )
        else:
            prompt_ids, completion_ids = generate_transformers_fallback(
                model.pretrained_model, tok, prompts, generation_kwargs
            )

        # Decode responses
        responses = tok.batch_decode(completion_ids, skip_special_tokens=True)
        
        batch["response"] = responses


        # Compute rewards
        def compute_rewards(batch):
            """Compute rewards for prompt-completion pairs using the modular reward system"""
            original_conversations = batch["original_conversation"]
            conversation_histories = batch["prompt"]
            responses = batch["response"]
            ground_truths = batch["ground_truth"]

            if hasattr(reward_calculator, 'calculate_batch_completion_rewards'):
                reward_values = reward_calculator.calculate_batch_completion_rewards(
                    original_conversations, conversation_histories, responses, ground_truths
                )
            else:
                reward_values = []
                for original_conversation, history, response, gt in zip(original_conversations, conversation_histories, responses, ground_truths):
                    reward = reward_calculator.calculate_single_completion_reward(original_conversation, history, response, gt)
                    reward_values.append(reward)
            
            rewards = []
            for reward_val in reward_values:
                rewards.append(torch.tensor(float(reward_val), device=trainer.accelerator.device))

            return rewards

        rewards = compute_rewards(batch)
        
        # Update batch with rewards and responses for PPO
        batch["reward"] = rewards

        # Run PPO step
        torch.cuda.empty_cache()
        
        try:
            stats = trainer.step(prompt_ids, completion_ids, rewards)
            trainer.log_stats(stats, batch, rewards, columns_to_log=["responses", "rewards"])
        
            mean_reward = np.mean([r.item() for r in rewards])
            print(f"PPO Step {step}: Mean Reward: {mean_reward:.4f}")
            
            # Log to wandb if available
            if args.wandb_project and os.environ.get("LOCAL_RANK", "0") == "0":
                wandb.log({
                    "step": step,
                    "mean_reward": mean_reward,
                    "max_reward": max([r.item() for r in rewards]),
                    "min_reward": min([r.item() for r in rewards]),
                })
                
        except Exception as e:
            print(f"Error in PPO step: {e}")
            continue
        
        torch.cuda.empty_cache()
            
        # Save checkpoint
        if step % args.save_steps == 0:
            trainer.save_pretrained(os.path.join(args.output_dir, f"step_{step}"))
            tok.save_pretrained(os.path.join(args.output_dir, f"step_{step}"))
        
        print(f"[Rank: {local_rank}] Step: {step}, Batch size: {len(prompts)}, Mean Reward: {np.mean([r.item() for r in rewards]):.4f}")

    # Cleanup
    reward_calculator.cleanup()

    # Final save
    trainer.save_pretrained(args.output_dir)
    tok.save_pretrained(args.output_dir)

    if args.push_to_hub and args.hf_org:
        repo = f"trajectory-ppo-{args.dataset_repo.replace('/', '_')}"
        trainer.push_to_hub(f"{args.hf_org}/{repo}", private=True)
        tok.push_to_hub(f"{args.hf_org}/{repo}", private=True)

    if args.wandb_project:
        wandb.finish()

if __name__ == "__main__":
    load_dotenv(".env")
    main()